WITH T AS(
    SELECT a.PARENT_ID as GRANDPARENT_ID, b.ID AS ID
    FROM ECOLI_DATA as a JOIN ECOLI_DATA as b on a.ID = b.PARENT_ID
)
SELECT b.ID
FROM ECOLI_DATA as a JOIN T as b on a.ID = b.GRANDPARENT_ID
WHERE a.PARENT_ID IS NULL
ORDER BY ID