WITH SIZEPERCENT AS (
    SELECT ID, 
    SIZE_OF_COLONY,
    NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) as PERCENT
    FROM ECOLI_DATA
)
SELECT ID,
CASE
    WHEN PERCENT=1 THEN 'CRITICAL'
    WHEN PERCENT=2 THEN 'HIGH'
    WHEN PERCENT=3 THEN 'MEDIUM'
    ELSE 'LOW'
END as COLONY_NAME
FROM SIZEPERCENT
ORDER BY ID
