WITH AVGTABLE as(
    SELECT a.EMP_NO as EMP_NO, 
    AVG(b.SCORE)
     as SCORE
    FROM HR_EMPLOYEES as a
    left JOIN HR_GRADE as b
    on a.EMP_NO = b.EMP_NO
    GROUP BY EMP_NO
)

SELECT a.EMP_NO as EMP_NO, 
a.EMP_NAME as EMP_NAME,
CASE
    WHEN b.SCORE>=96 THEN 'S'
    WHEN b.SCORE>=90 THEN 'A'
    WHEN b.SCORE>=80 THEN 'B'
    ELSE 'C'
END
 as GRADE,
 CASE
    WHEN b.SCORE>=96 THEN a.SAL*0.2
    WHEN b.SCORE>=90 THEN a.SAL*0.15
    WHEN b.SCORE>=80 THEN a.SAL*0.1
    ELSE 0
END
as BONUS
FROM HR_EMPLOYEES as a
JOIN AVGTABLE as b
on a.EMP_NO = b.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO
