WITH MAXSIZE AS(
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR
)
SELECT a.YEAR, (m.MAX_SIZE-a.SIZE) as YEAR_DEV, a.ID as ID
FROM (SELECT ID, YEAR(DIFFERENTIATION_DATE) as YEAR, SIZE_OF_COLONY as SIZE FROM ECOLI_DATA )as a JOIN MAXSIZE as m on a.YEAR = m.YEAR
ORDER BY a.YEAR, YEAR_DEV 
