WITH MAXSIZE AS(
    SELECT MAX(LENGTH) as LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT a.ID, b.FISH_NAME, C.LENGTH
FROM FISH_INFO as a JOIN FISH_NAME_INFO as b on a.FISH_TYPE = b.FISH_TYPE
JOIN MAXSIZE as c on a.FISH_TYPE = c.FISH_TYPE
WHERE a.LENGTH = c.LENGTH