WITH AVGLENGTH as(
    SELECT AVG(LENGTH) as AVG_LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT COUNT(a.ID) as FISH_COUNT, MAX(a.LENGTH) as MAX_LENGTH, a.FISH_TYPE as FISH_TYPE
FROM FISH_INFO as a
JOIN AVGLENGTH as b
on a.FISH_TYPE = b.FISH_TYPE
WHERE b.AVG_LENGTH>=33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE